export const products = [
	{
		name: 'Model UNG-05A: Winter jacket for engineers',
		description: 'Color: dark blue/black',
		images: '/clothes5.png',
		secondImg: '/clothes1.png',
		slug: 'model-ung-05a-winter-jacket-for-engineers',
		price: 300.0,
		category: 'Winter',
	},
	{
		name: 'Model UNG-07: Summer set for workers',
		description: 'Color: dark blue/black',
		images: '/clothes2.png',
		secondImg: '/clothes1.png',
		slug: 'model-ung-07-summer-set-for-workers',
		price: 280.0,
		category: 'Winter',
	},
	{
		name: 'Model UNG-09X: Urban Explorer Kit',
		description: 'Color: grey/orange',
		images: '/clothes3.png',
		secondImg: '/clothes2.png',
		slug: 'model-ung-09x-urban-explorer-kit',
		price: 290.0,
		category: 'City',
	},
	{
		name: 'Model UNG-08K: Mountain Climber Essentials',
		description: 'Color: blue/grey',
		images: '/clothes4.png',
		secondImg: '/clothes5.png',
		slug: 'model-ung-08k-mountain-climber-essentials',
		price: 420.0,
		category: 'Outdoor',
	},
	{
		name: 'Model UNG-07A: Flight kit for workers',
		description: 'Color: grey/red',
		images: '/clothes4.png',
		secondImg: '/clothes3.png',
		slug: 'model-ung-07a-flight-kit-for-workers',
		price: 320.0,
		category: 'Summer',
	},
	{
		name: 'Model UNG-01S: Flight Kit For Senior Management',
		description: 'Color: grey/red',
		images: '/clothes1.png',
		secondImg: '/clothes3.png',
		slug: 'model-ung-01s-flight-kit-for-senior-management',
		price: 320.0,
		category: 'Summer',
	},
	{
		name: 'Model UNG-02B: Waterproof Jacket for Hikers',
		description: 'Color: green/black',
		images: '/clothes1.png',
		secondImg: '/clothes4.png',
		slug: 'model-ung-02b-waterproof-jacket-for-hikers',
		price: 250.0,
		category: 'Outdoor',
	},
	{
		name: 'Model UNG-03C: Tactical Gear Set for Adventurers',
		description: 'Color: camouflage',
		images: '/clothes2.png',
		secondImg: '/clothes5.png',
		slug: 'model-ung-03c-tactical-gear-set-for-adventurers',
		price: 380.0,
		category: 'Adventure',
	},
]
